OOP Library/ Unit tests
Munyabelden/Oop_Library pull request #8
Opened 2023-05-31 14:59 UTC by Munyabelden

### PR Description

- [ ] Install rspec and add to the Gemfile
- [ ] Create a folder name specs to store all my test files
- [ ] Tested classes:
         - Person
         - Student
         - Classroom
         - Rantal
         - Book
         - Teacher
         - CapitalizeDecorator
         - TrimmerDecorator
 
**Thank you for the review😊**

2023-05-31 18:32 UTC, Munsa1 requested changes
Hi @Munyabelden @Tracy-miranj, 
![required-changes-1](https://github.com/Munyabelden/Oop_Library/assets/81932478/b87e9cf6-673c-432c-afc3-ec76a3d42a8f)


Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>

## Highlights
All Passing Tests :heavy_check_mark: 
Correct Git Flow :heavy_check_mark: 
Descriptive Branch Name :heavy_check_mark: 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- x
- y
- z

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-31 18:32 UTC, Munsa1 commented on specs/person_spec.rb
> +require_relative '../person'
- [ ] It's a requirement to make sure to check there is an 'it' block for each class method (at least). Kindly add this for the `add_rental` method.

2023-05-31 18:32 UTC, Munsa1 commented on specs/capitalize_decorator_spec.rb
> +require_relative '../capitalize_decorator'
- [ ] Kindly add tests for all classes that you created while implementing the Decorator design pattern as this is a requirement.
Please add tests for the `nameable..rb` class

![image](https://github.com/Munyabelden/Oop_Library/assets/81932478/3af5d913-422d-4c52-8d96-1d0568a0582d)

2023-05-31 18:32 UTC, Munsa1 requested changes
Hi @Munyabelden @Tracy-miranj, 
![required-changes-1](https://github.com/Munyabelden/Oop_Library/assets/81932478/b87e9cf6-673c-432c-afc3-ec76a3d42a8f)


Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>

## Highlights
All Passing Tests :heavy_check_mark: 
Correct Git Flow :heavy_check_mark: 
Descriptive Branch Name :heavy_check_mark: 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- x
- y
- z

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-01 08:21 UTC, Ismailco approved these changes
### Hi @Munyabelden, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![cr-approve](https://user-images.githubusercontent.com/25227022/165483662-7b06c812-4cc0-40b9-a84c-4729d4cf10c3.gif)


## Highlights

✔️  No linter errors
✔️ Used Gitflow
✔️ Work documented professionally

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-01 11:54 UTC, merged